<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="macadmins-MacBook-Pro-2.local" ignored="0" name="Default test" tests="10" failures="2" timestamp="23 Jan 2018 00:24:37 GMT" time="416.966" errors="0">
  <testcase name="AnalyticsNameCheck0001" time="0.081" classname="TestNG.TestAnalyticsNameInJson">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false],
	expected [true] but found [false],
	expected [true] but found [false],
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:expected [true] but found [false],expected [true] but found [false],expected [true] but found [false],expected [true] but found [false]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at TestNG.TestAnalyticsNameInJson.AnalyticsNameCheck0001(TestAnalyticsNameInJson.java:81)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- AnalyticsNameCheck0001 -->
  <testcase name="executeJSONFromRESTAPI" time="101.082" classname="TestNG.JSONParserCMSResponse">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:expected [1] but found [0]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.adidas.automation.RestAPICall.callRestfulAPI(RestAPICall.java:127)at TestNG.JSONParserCMSResponse.executeJSONFromRESTAPI(JSONParserCMSResponse.java:56)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- executeJSONFromRESTAPI -->
  <testcase name="ImageRespponseCode0001" time="62.724" classname="TestNG.TestImageLoadingResponse"/>
  <testcase name="FirefoxTestUIAdidas0001" time="25.238" classname="TestNG.FirefoxTestUIAdidasHomePage"/>
  <testcase name="FirefoxTestUIAdidas0002" time="43.671" classname="TestNG.FirefoxTestUIAdidasHomePage"/>
  <testcase name="FirefoxTestUIAdidas0003" time="55.531" classname="TestNG.FirefoxTestUIAdidasHomePage"/>
  <testcase name="ChromeTestUIAdidas0001" time="30.088" classname="TestNG.ChromeTestUIAdidasHomePage"/>
  <testcase name="ChromeTestUIAdidas0002" time="43.415" classname="TestNG.ChromeTestUIAdidasHomePage"/>
  <testcase name="ChromeTestUIAdidas0003" time="55.08" classname="TestNG.ChromeTestUIAdidasHomePage"/>
  <testcase name="executeTest1" time="0.006" classname="TestNG.JsonsNEST"/>
</testsuite> <!-- Default test -->
